package com.semantyca.nb.core.dataengine.jpa.dao.exception;

public enum DAOExceptionType {
    ENTITY_NOT_FOUND, UNIQUE_VIOLATION, NON_ENTITY_EXCEPTION, NOT_NULL_VIOLATION, NOT_UNIQUE_RESULT,
    INTERNAL_PERSISTENCE_EXCEPTION, VIOLATES_FOREIGN_KEY, FILE_TOO_LARGE, VALUE_TOO_LONG,
    ID_IS_NULL, NO_ROLE;

}
